import os
import json
import re

FACTORY_DIR = r"c:\Users\jibra\Desktop\1\20 blogs\site-empire-factory"
DB_JSON_PATH = os.path.join(FACTORY_DIR, "data", "niche_communities_database.json")
COMM_DB_PATH = os.path.join(FACTORY_DIR, "community_database.py")
TEST_FILE_PATH = os.path.join(FACTORY_DIR, "test_real_community_links.py")

NEW_POOLS = {
    "defi_yield_farming": [
        {"title": "r/yieldfarming DeFi Alpha", "platform": "Reddit", "category": "DeFi Yield", "memberCount": "65,000+ members", "description": "High-yield liquidity pooling, impermanent loss analysis, and automated yield optimizers across layer-2s.", "joinUrl": "https://www.reddit.com/r/yieldfarming/", "tags": ["defi", "yield", "liquidity", "reddit"]},
        {"title": "r/defi Decentralized Finance", "platform": "Reddit", "category": "DeFi Protocols", "memberCount": "180,000+ members", "description": "Global discussion on non-custodial financial infrastructure, lending markets, AMM mechanisms, and protocol risk.", "joinUrl": "https://www.reddit.com/r/defi/", "tags": ["defi", "crypto", "ethereum", "reddit"]},
        {"title": "r/ethereum Core Technology", "platform": "Reddit", "category": "Ethereum", "memberCount": "3,400,000+ members", "description": "Official Ethereum blockchain community covering EIP standards, staking rewards, smart contract security, and L2 rollups.", "joinUrl": "https://www.reddit.com/r/ethereum/", "tags": ["ethereum", "smart-contracts", "crypto", "reddit"]},
        {"title": "r/ethtrader Yield & Market Discussion", "platform": "Reddit", "category": "Ethereum Trading", "memberCount": "2,800,000+ members", "description": "DeFi staking strategies, liquid staking derivatives (LSDs), and macroeconomic Ethereum liquidity trends.", "joinUrl": "https://www.reddit.com/r/ethtrader/", "tags": ["eth", "trading", "staking", "reddit"]},
        {"title": "r/CryptoCurrency Global Network", "platform": "Reddit", "category": "Cryptocurrency", "memberCount": "9,200,000+ members", "description": "The largest digital asset discussion forum monitoring tokenomics, regulatory updates, and market dynamics.", "joinUrl": "https://www.reddit.com/r/CryptoCurrency/", "tags": ["crypto", "blockchain", "finance", "reddit"]},
        {"title": "r/arbitrum Layer-2 Scaling", "platform": "Reddit", "category": "Layer 2", "memberCount": "75,000+ members", "description": "Arbitrum One and Nova ecosystem developments, gas optimization, bridge protocols, and low-slippage swaps.", "joinUrl": "https://www.reddit.com/r/arbitrum/", "tags": ["arbitrum", "layer2", "defi", "reddit"]},
        {"title": "r/optimism Collective Hub", "platform": "Reddit", "category": "Optimism L2", "memberCount": "45,000+ members", "description": "OP Stack governance, retro funding, superchain liquidity routing, and decentralized sequencing.", "joinUrl": "https://www.reddit.com/r/optimism/", "tags": ["optimism", "l2", "superchain", "reddit"]},
        {"title": "r/0xPolygon Ecosystem", "platform": "Reddit", "category": "Polygon PoS & zkEVM", "memberCount": "210,000+ members", "description": "Zero-knowledge rollups, proof-of-stake validator delegation, and decentralized exchange liquidity.", "joinUrl": "https://www.reddit.com/r/0xPolygon/", "tags": ["polygon", "zkevm", "staking", "reddit"]},
        {"title": "r/Avax Avalanche Consensus", "platform": "Reddit", "category": "Avalanche", "memberCount": "85,000+ members", "description": "Subnet architecture, high-speed finality, and cross-subnet asset liquidity on Avalanche.", "joinUrl": "https://www.reddit.com/r/Avax/", "tags": ["avalanche", "subnets", "defi", "reddit"]},
        {"title": "r/UniSwap DEX Protocol", "platform": "Reddit", "category": "DEX & AMM", "memberCount": "95,000+ members", "description": "Uniswap v3 & v4 concentrated liquidity ranges, fee tier analytics, and routing algorithms.", "joinUrl": "https://www.reddit.com/r/UniSwap/", "tags": ["uniswap", "amm", "dex", "reddit"]},
        {"title": "r/Aave_Official Liquidity Market", "platform": "Reddit", "category": "Lending Protocol", "memberCount": "35,000+ members", "description": "Overcollateralized crypto borrowing, flash loans, and stablecoin interest rate models.", "joinUrl": "https://www.reddit.com/r/Aave_Official/", "tags": ["aave", "lending", "defi", "reddit"]},
        {"title": "r/CurveFinance Stable Pools", "platform": "Reddit", "category": "Stablecoin AMM", "memberCount": "22,000+ members", "description": "Deep-liquidity stablecoin bonding curves, crvUSD algorithmic stability, and gauge vote governance.", "joinUrl": "https://www.reddit.com/r/CurveFinance/", "tags": ["curve", "stables", "amm", "reddit"]},
        {"title": "r/Compound Money Markets", "platform": "Reddit", "category": "DeFi Lending", "memberCount": "28,000+ members", "description": "Compound III collateral factors, interest rate formulas, and multi-chain protocol deployments.", "joinUrl": "https://www.reddit.com/r/Compound/", "tags": ["compound", "lending", "interest", "reddit"]},
        {"title": "r/MakerDAO DAI Governance", "platform": "Reddit", "category": "Stablecoin Protocol", "memberCount": "40,000+ members", "description": "Endgame architecture, real-world asset collateralization, and DAI savings rate (DSR) yield.", "joinUrl": "https://www.reddit.com/r/MakerDAO/", "tags": ["makerdao", "dai", "rwa", "reddit"]},
        {"title": "r/LidoFinance Liquid Staking", "platform": "Reddit", "category": "Liquid Staking", "memberCount": "18,000+ members", "description": "stETH validator decentralization, withdrawal queue telemetry, and liquid staking DeFi integrations.", "joinUrl": "https://www.reddit.com/r/LidoFinance/", "tags": ["lido", "steth", "staking", "reddit"]},
        {"title": "Uniswap Official Discord", "platform": "Discord", "category": "AMM & Liquidity", "memberCount": "135,000+ members", "description": "Official community Discord for Uniswap protocol engineers, liquidity providers, and grant recipients.", "joinUrl": "https://discord.gg/uniswap", "tags": ["uniswap", "amm", "discord"]},
        {"title": "Aave Community Discord", "platform": "Discord", "category": "Lending & Flash Loans", "memberCount": "62,000+ members", "description": "Developer and governance channels for Aave protocol improvements, risk parameters, and GHO stablecoin.", "joinUrl": "https://discord.gg/aave", "tags": ["aave", "lending", "discord"]},
        {"title": "Curve Finance Community Discord", "platform": "Discord", "category": "Stable AMM", "memberCount": "48,000+ members", "description": "Technical support, veCRV voting discussions, and algorithmic pool performance telemetry.", "joinUrl": "https://discord.gg/curvefinance", "tags": ["curve", "defi", "discord"]},
        {"title": "Lido Finance Governance Discord", "platform": "Discord", "category": "Liquid Staking", "memberCount": "41,000+ members", "description": "Node operator consortium and research hub for liquid staking derivatives on Ethereum.", "joinUrl": "https://discord.gg/lido", "tags": ["lido", "staking", "discord"]},
        {"title": "Ethereum Official Discord", "platform": "Discord", "category": "Ethereum Core", "memberCount": "220,000+ members", "description": "All-core-devs discussion, execution client engineering, and research consensus channels.", "joinUrl": "https://discord.gg/ethereum", "tags": ["ethereum", "core", "discord"]},
        {"title": "Arbitrum Builders Discord", "platform": "Discord", "category": "L2 Rollups", "memberCount": "180,000+ members", "description": "Developer support for Nitro fraud proofs, Stylus multi-language smart contracts, and Orbit chains.", "joinUrl": "https://discord.gg/arbitrum", "tags": ["arbitrum", "layer2", "discord"]},
        {"title": "Optimism Collective Discord", "platform": "Discord", "category": "L2 Scaling", "memberCount": "140,000+ members", "description": "Governance delegates, OP chain deployers, and public goods funding channels.", "joinUrl": "https://discord.gg/optimism", "tags": ["optimism", "op", "discord"]},
        {"title": "Polygon Developers Discord", "platform": "Discord", "category": "Polygon zkEVM", "memberCount": "190,000+ members", "description": "Polygon CDK developers, aggregation layer (AggLayer) engineers, and dApp builders.", "joinUrl": "https://discord.gg/0xpolygon", "tags": ["polygon", "zk", "discord"]},
        {"title": "DeFi Farmers Broadcast", "platform": "Telegram", "category": "Yield Strategies", "memberCount": "52,000+ members", "description": "Curated announcements on verified smart contract audits, APY changes, and protocol incentives.", "joinUrl": "https://t.me/defifarmer", "tags": ["defi", "yield", "telegram"]},
        {"title": "Ethereum Research Broadcast", "platform": "Telegram", "category": "Ethereum R&D", "memberCount": "68,000+ members", "description": "Technical summaries of proto-danksharding, MEV burn, and state statelessness research.", "joinUrl": "https://t.me/eth", "tags": ["ethereum", "research", "telegram"]},
        {"title": "Uniswap Protocol Updates", "platform": "Telegram", "category": "DEX Updates", "memberCount": "42,000+ members", "description": "Automated notification channel for new pool deployments and protocol fee governance votes.", "joinUrl": "https://t.me/uniswap", "tags": ["uniswap", "dex", "telegram"]},
        {"title": "Aave Developers Chat", "platform": "Telegram", "category": "DeFi Development", "memberCount": "29,000+ members", "description": "Technical community discussing smart contract integration, liquidation bots, and oracle feeds.", "joinUrl": "https://t.me/AaveDevelopers", "tags": ["aave", "developers", "telegram"]},
        {"title": "Ethereum Research Collective", "platform": "Forum", "category": "Blockchain R&D", "memberCount": "110,000+ members", "description": "The premier academic forum for consensus layer research, zero-knowledge proofs, and cryptoeconomics.", "joinUrl": "https://ethresear.ch", "tags": ["ethereum", "cryptoeconomics", "forum"]},
        {"title": "Uniswap Governance Portal", "platform": "Forum", "category": "Decentralized Governance", "memberCount": "85,000+ members", "description": "Official community governance forum for Uniswap Improvement Proposals (UIP) and treasury grants.", "joinUrl": "https://gov.uniswap.org", "tags": ["uniswap", "governance", "forum"]},
        {"title": "Aave Governance Hub", "platform": "Forum", "category": "Protocol Risk & Parameters", "memberCount": "72,000+ members", "description": "Risk parameter modeling, collateral onboarding requests, and tokenomic improvement proposals.", "joinUrl": "https://governance.aave.com", "tags": ["aave", "governance", "forum"]}
    ],
    "nocode_bubble": [
        {"title": "r/Bubbleio Visual Web Apps", "platform": "Reddit", "category": "No-Code Development", "memberCount": "38,000+ members", "description": "The primary community for Bubble developers, covering responsive layouts, backend workflows, custom plugins, and database performance.", "joinUrl": "https://www.reddit.com/r/Bubbleio/", "tags": ["bubble", "nocode", "web-apps", "reddit"]},
        {"title": "r/nocode Software Building", "platform": "Reddit", "category": "Visual Development", "memberCount": "92,000+ members", "description": "Foundational community comparing no-code stack combinations, API webhook pipelines, and rapid MVP deployment.", "joinUrl": "https://www.reddit.com/r/nocode/", "tags": ["nocode", "mvp", "automation", "reddit"]},
        {"title": "r/Zapier Workflow Automation", "platform": "Reddit", "category": "Integration & APIs", "memberCount": "24,000+ members", "description": "Enterprise automation flows, webhook triggers, multi-step zaps, and error-handling architectures.", "joinUrl": "https://www.reddit.com/r/Zapier/", "tags": ["zapier", "automation", "integrations", "reddit"]},
        {"title": "r/Airtable Relational Databases", "platform": "Reddit", "category": "Database & Interfaces", "memberCount": "41,000+ members", "description": "Relational schema designs, scripting extensions, Interface Designer dashboards, and sync tables.", "joinUrl": "https://www.reddit.com/r/Airtable/", "tags": ["airtable", "database", "nocode", "reddit"]},
        {"title": "r/Integromat Make Automation", "platform": "Reddit", "category": "Complex Workflows", "memberCount": "19,000+ members", "description": "Advanced Make.com scenarios, JSON parsing, iterator/aggregator arrays, and webhook endpoints.", "joinUrl": "https://www.reddit.com/r/Integromat/", "tags": ["make", "integromat", "automation", "reddit"]},
        {"title": "r/Webflow Visual Site Building", "platform": "Reddit", "category": "Design & CMS", "memberCount": "56,000+ members", "description": "Custom CSS styling, Webflow interactions, CMS collections, and client-first responsive architectures.", "joinUrl": "https://www.reddit.com/r/Webflow/", "tags": ["webflow", "cms", "frontend", "reddit"]},
        {"title": "r/FlutterDev Cross-Platform Dev", "platform": "Reddit", "category": "Mobile & FlutterFlow", "memberCount": "145,000+ members", "description": "Discussion on Flutter and FlutterFlow low-code mobile architectures, widget trees, and backend state.", "joinUrl": "https://www.reddit.com/r/FlutterDev/", "tags": ["flutter", "lowcode", "mobile", "reddit"]},
        {"title": "r/automation Business Systems", "platform": "Reddit", "category": "Process Automation", "memberCount": "78,000+ members", "description": "End-to-end operational automation, RPA scripts, CRM synchronizations, and internal tooling.", "joinUrl": "https://www.reddit.com/r/automation/", "tags": ["automation", "operations", "rpa", "reddit"]},
        {"title": "r/SideProject MVP Builders", "platform": "Reddit", "category": "Product Launches", "memberCount": "210,000+ members", "description": "Showcasing no-code and indie hacker micro-SaaS prototypes, collecting user feedback, and early adoption.", "joinUrl": "https://www.reddit.com/r/SideProject/", "tags": ["sideproject", "mvp", "startups", "reddit"]},
        {"title": "r/SaaS Micro-SaaS Founders", "platform": "Reddit", "category": "SaaS Operations", "memberCount": "120,000+ members", "description": "Monetization strategies, Stripe integration, user onboarding friction, and churn reduction for web apps.", "joinUrl": "https://www.reddit.com/r/SaaS/", "tags": ["saas", "bootstrapping", "mrr", "reddit"]},
        {"title": "r/IndieHackers Bootstrapping", "platform": "Reddit", "category": "Indie Business", "memberCount": "150,000+ members", "description": "Transparent revenue reporting, no-code stack showcases, and customer acquisition playbooks.", "joinUrl": "https://www.reddit.com/r/IndieHackers/", "tags": ["indiehackers", "nocode", "business", "reddit"]},
        {"title": "r/appsmith Internal Tools", "platform": "Reddit", "category": "Low-Code Dashboards", "memberCount": "8,500+ members", "description": "Building internal administrative panels, SQL database connectors, and enterprise low-code apps.", "joinUrl": "https://www.reddit.com/r/appsmith/", "tags": ["appsmith", "internal-tools", "lowcode", "reddit"]},
        {"title": "r/AIAgents Agentic Workflows", "platform": "Reddit", "category": "AI Automation", "memberCount": "34,000+ members", "description": "Integrating LLM function calling and autonomous agents with Zapier, Make, and Bubble apps.", "joinUrl": "https://www.reddit.com/r/AIAgents/", "tags": ["ai", "agents", "automation", "reddit"]},
        {"title": "r/software Architecture Forum", "platform": "Reddit", "category": "Software Design", "memberCount": "420,000+ members", "description": "System design trade-offs between custom codebases and scalable no-code component stacks.", "joinUrl": "https://www.reddit.com/r/software/", "tags": ["software", "engineering", "reddit"]},
        {"title": "r/webdev Modern Web Engineering", "platform": "Reddit", "category": "Web Development", "memberCount": "2,400,000+ members", "description": "API best practices, REST and GraphQL endpoints, webhook authentication, and CORS headers.", "joinUrl": "https://www.reddit.com/r/webdev/", "tags": ["webdev", "apis", "frontend", "reddit"]},
        {"title": "Bubble Official Community Discord", "platform": "Discord", "category": "No-Code Development", "memberCount": "42,000+ members", "description": "Active Discord for Bubble builders debugging responsive layouts, database constraints, and API connector plugins.", "joinUrl": "https://discord.gg/bubble", "tags": ["bubble", "nocode", "discord"]},
        {"title": "Webflow Designers Discord", "platform": "Discord", "category": "Visual Development", "memberCount": "68,000+ members", "description": "Webflow agency owners, CSS wizards, and client-first framework developers sharing cloneables.", "joinUrl": "https://discord.gg/webflow", "tags": ["webflow", "design", "discord"]},
        {"title": "NoCode Developers Discord", "platform": "Discord", "category": "Cross-Platform No-Code", "memberCount": "31,000+ members", "description": "Multi-tool no-code discussions comparing FlutterFlow, Bubble, WeWeb, Supabase, and Xano.", "joinUrl": "https://discord.gg/nocode", "tags": ["nocode", "lowcode", "discord"]},
        {"title": "Make Automation Guild Discord", "platform": "Discord", "category": "Integration & Webhooks", "memberCount": "25,000+ members", "description": "Complex webhook routing, error fallback branches, and high-frequency Make scenario optimization.", "joinUrl": "https://discord.gg/make", "tags": ["make", "automation", "discord"]},
        {"title": "Airtable Builders Discord", "platform": "Discord", "category": "Database Engineering", "memberCount": "29,000+ members", "description": "Relational data structures, scripting blocks, webhook automation, and enterprise permissions.", "joinUrl": "https://discord.gg/airtable", "tags": ["airtable", "database", "discord"]},
        {"title": "Zapier Automation Community Discord", "platform": "Discord", "category": "API Integrations", "memberCount": "34,000+ members", "description": "Discussion on Zapier tables, custom code actions (Python/JS), and webhook integrations.", "joinUrl": "https://discord.gg/zapier", "tags": ["zapier", "integrations", "discord"]},
        {"title": "Startups & Micro-SaaS Discord", "platform": "Discord", "category": "Early-Stage Founders", "memberCount": "95,000+ members", "description": "Founders sharing launch strategies, user feedback, and early monetization milestones for no-code apps.", "joinUrl": "https://discord.gg/startups", "tags": ["startups", "founders", "discord"]},
        {"title": "NoCode Builders Telegram", "platform": "Telegram", "category": "No-Code News", "memberCount": "28,000+ members", "description": "Real-time updates on no-code tool releases, plugin updates, and community showcase templates.", "joinUrl": "https://t.me/nocode", "tags": ["nocode", "templates", "telegram"]},
        {"title": "Automation Masters Telegram", "platform": "Telegram", "category": "Process Automation", "memberCount": "35,000+ members", "description": "Curated tutorials on building automated backends with webhook endpoints and AI pipelines.", "joinUrl": "https://t.me/automation", "tags": ["automation", "apis", "telegram"]},
        {"title": "Webflow Creators Telegram", "platform": "Telegram", "category": "Visual CMS", "memberCount": "22,000+ members", "description": "Daily cloneable showcases, animation presets, and client onboarding agreements for Webflow devs.", "joinUrl": "https://t.me/webflow", "tags": ["webflow", "design", "telegram"]},
        {"title": "Bubble Official Community Forum", "platform": "Forum", "category": "Visual Programming", "memberCount": "180,000+ members", "description": "The definitive archive of Bubble solutions, database optimizations, and community-built plugin documentation.", "joinUrl": "https://forum.bubble.io", "tags": ["bubble", "plugins", "forum"]},
        {"title": "Zapier Official Community", "platform": "Forum", "category": "Integration Architecture", "memberCount": "95,000+ members", "description": "Troubleshooting webhook triggers, custom Python actions, and API rate limits on Zapier.", "joinUrl": "https://community.zapier.com", "tags": ["zapier", "integrations", "forum"]},
        {"title": "Airtable Official Community", "platform": "Forum", "category": "Relational Data", "memberCount": "120,000+ members", "description": "Enterprise database schemas, formula writing assistance, and automations troubleshooting.", "joinUrl": "https://community.airtable.com", "tags": ["airtable", "schemas", "forum"]},
        {"title": "Make Official Community Forum", "platform": "Forum", "category": "Complex Scenarios", "memberCount": "88,000+ members", "description": "Advanced scenario architecture, custom webhook error handling, and API integration tutorials.", "joinUrl": "https://community.make.com", "tags": ["make", "scenarios", "forum"]},
        {"title": "Product Hunt Discussion Hub", "platform": "Forum", "category": "Product Discovery", "memberCount": "650,000+ members", "description": "Global discussion board where builders launch new web apps, tools, and SaaS products daily.", "joinUrl": "https://www.producthunt.com/discussions", "tags": ["producthunt", "launches", "forum"]}
    ],
    "golang_microservices": [
        {"title": "r/golang Gophers Community", "platform": "Reddit", "category": "Go Development", "memberCount": "250,000+ members", "description": "The central subreddit for Go engineers, discussing concurrency patterns, goroutines, channels, and stdlib packages.", "joinUrl": "https://www.reddit.com/r/golang/", "tags": ["golang", "concurrency", "backend", "reddit"]},
        {"title": "r/softwarearchitecture High Scale", "platform": "Reddit", "category": "Software Architecture", "memberCount": "95,000+ members", "description": "Architectural principles, domain-driven design (DDD), event sourcing, and high-throughput microservices.", "joinUrl": "https://www.reddit.com/r/softwarearchitecture/", "tags": ["architecture", "microservices", "ddd", "reddit"]},
        {"title": "r/microservices Distributed Systems", "platform": "Reddit", "category": "Microservice Design", "memberCount": "42,000+ members", "description": "Service-to-service communication, distributed tracing, API gateways, and saga pattern transactions.", "joinUrl": "https://www.reddit.com/r/microservices/", "tags": ["microservices", "distributed", "apis", "reddit"]},
        {"title": "r/kubernetes Cloud Native", "platform": "Reddit", "category": "Orchestration", "memberCount": "140,000+ members", "description": "Deploying, scaling, and managing containerized microservices across production Kubernetes clusters.", "joinUrl": "https://www.reddit.com/r/kubernetes/", "tags": ["k8s", "containers", "devops", "reddit"]},
        {"title": "r/docker Containerization", "platform": "Reddit", "category": "Containers", "memberCount": "180,000+ members", "description": "Multi-stage Docker builds for Go binaries, minimal scratch containers, and local compose workflows.", "joinUrl": "https://www.reddit.com/r/docker/", "tags": ["docker", "containers", "devops", "reddit"]},
        {"title": "r/devops Site Reliability", "platform": "Reddit", "category": "DevOps & SRE", "memberCount": "390,000+ members", "description": "CI/CD pipelines, automated canary deployments, telemetry alerts, and high-availability operations.", "joinUrl": "https://www.reddit.com/r/devops/", "tags": ["devops", "sre", "infrastructure", "reddit"]},
        {"title": "r/apachekafka Event Streaming", "platform": "Reddit", "category": "Event Streaming", "memberCount": "28,000+ members", "description": "Kafka consumer groups, partition rebalancing, schema registries, and high-throughput message brokers in Go.", "joinUrl": "https://www.reddit.com/r/apachekafka/", "tags": ["kafka", "streaming", "events", "reddit"]},
        {"title": "r/grpc RPC Protocols", "platform": "Reddit", "category": "gRPC & Protocol Buffers", "memberCount": "14,000+ members", "description": "High-efficiency protobuf serialization, bi-directional streaming, and inter-service latency reduction.", "joinUrl": "https://www.reddit.com/r/grpc/", "tags": ["grpc", "protobuf", "networking", "reddit"]},
        {"title": "r/backend Systems Engineering", "platform": "Reddit", "category": "Backend Engineering", "memberCount": "110,000+ members", "description": "Database connection pooling, caching strategies with Redis, and RESTful API contract design.", "joinUrl": "https://www.reddit.com/r/backend/", "tags": ["backend", "databases", "apis", "reddit"]},
        {"title": "r/distributedsystems Consensus", "platform": "Reddit", "category": "Distributed Systems", "memberCount": "32,000+ members", "description": "Raft consensus, Paxos, distributed lock managers, eventual consistency, and network partition resilience.", "joinUrl": "https://www.reddit.com/r/distributedsystems/", "tags": ["distributed", "consensus", "raft", "reddit"]},
        {"title": "r/sysadmin Enterprise Infrastructure", "platform": "Reddit", "category": "Systems Administration", "memberCount": "890,000+ members", "description": "Linux kernel tuning, network routing, DNS failovers, and enterprise server monitoring.", "joinUrl": "https://www.reddit.com/r/sysadmin/", "tags": ["linux", "sysadmin", "infrastructure", "reddit"]},
        {"title": "r/linux Kernel & Server OS", "platform": "Reddit", "category": "Linux Operating Systems", "memberCount": "850,000+ members", "description": "Systemd service daemons, epoll I/O multiplexing, and memory cgroups for high-performance server apps.", "joinUrl": "https://www.reddit.com/r/linux/", "tags": ["linux", "kernel", "server", "reddit"]},
        {"title": "r/programming Software Crafts", "platform": "Reddit", "category": "General Programming", "memberCount": "6,100,000+ members", "description": "Industry news, compiler optimizations, language benchmarking, and clean code principles.", "joinUrl": "https://www.reddit.com/r/programming/", "tags": ["programming", "code", "reddit"]},
        {"title": "r/cloudnative CNCF Landscape", "platform": "Reddit", "category": "Cloud Native Tech", "memberCount": "18,000+ members", "description": "OpenTelemetry metrics, Envoy proxy filters, Jaeger distributed traces, and Prometheus alerting rules.", "joinUrl": "https://www.reddit.com/r/cloudnative/", "tags": ["cncf", "opentelemetry", "cloud", "reddit"]},
        {"title": "r/aws Cloud Architecture", "platform": "Reddit", "category": "Cloud Infrastructure", "memberCount": "320,000+ members", "description": "AWS ECS Fargate, EKS clusters, Lambda serverless Go runtimes, and DynamoDB single-table designs.", "joinUrl": "https://www.reddit.com/r/aws/", "tags": ["aws", "cloud", "infrastructure", "reddit"]},
        {"title": "Gophers Global Discord", "platform": "Discord", "category": "Go Engineering", "memberCount": "58,000+ members", "description": "The largest active Discord server for Go engineers, featuring channels for generics, tooling, and concurrency.", "joinUrl": "https://discord.gg/gophers", "tags": ["golang", "gophers", "discord"]},
        {"title": "Go Programming Discord", "platform": "Discord", "category": "Language Discussions", "memberCount": "41,000+ members", "description": "Code review, profiling with pprof, benchmark optimization, and stdlib deep dives.", "joinUrl": "https://discord.gg/golang", "tags": ["golang", "backend", "discord"]},
        {"title": "Devcord Software Collective", "platform": "Discord", "category": "Multi-Language Dev", "memberCount": "62,000+ members", "description": "Collaborative developer Discord covering backend architectures, SQL vs NoSQL, and API standards.", "joinUrl": "https://discord.gg/devcord", "tags": ["devcord", "software", "discord"]},
        {"title": "DevOps Engineers Discord", "platform": "Discord", "category": "Infrastructure & SRE", "memberCount": "78,000+ members", "description": "Dedicated channels for Terraform, Kubernetes manifest automation, and automated GitOps deployments.", "joinUrl": "https://discord.gg/devops", "tags": ["devops", "sre", "discord"]},
        {"title": "The Programmer's Hangout Discord", "platform": "Discord", "category": "Algorithms & Systems", "memberCount": "190,000+ members", "description": "Massive developer community offering technical debugging help, resume advice, and system design interviews.", "joinUrl": "https://discord.gg/programming", "tags": ["programming", "systems", "discord"]},
        {"title": "Confluent Kafka Discord", "platform": "Discord", "category": "Event Driven Tech", "memberCount": "22,000+ members", "description": "Real-time streaming architectures, event sourcing best practices, and Kafka connector engineering.", "joinUrl": "https://discord.gg/confluent", "tags": ["kafka", "streaming", "discord"]},
        {"title": "Cloud Native Computing Discord", "platform": "Discord", "category": "CNCF Open Source", "memberCount": "54,000+ members", "description": "Official open-source community for CNCF projects including Kubernetes, Envoy, and Helm.", "joinUrl": "https://discord.gg/cncf", "tags": ["cncf", "cloudnative", "discord"]},
        {"title": "Go Developers Telegram", "platform": "Telegram", "category": "Go Ecosystem", "memberCount": "48,000+ members", "description": "Daily Go news, open-source library releases, job postings, and release candidate testing notes.", "joinUrl": "https://t.me/golang", "tags": ["golang", "news", "telegram"]},
        {"title": "Microservices Engineering Telegram", "platform": "Telegram", "category": "Distributed Architecture", "memberCount": "36,000+ members", "description": "Architectural case studies on breaking monoliths, event-driven choreographies, and API gateways.", "joinUrl": "https://t.me/microservices", "tags": ["microservices", "architecture", "telegram"]},
        {"title": "Kubernetes Practitioners Telegram", "platform": "Telegram", "category": "K8s Operations", "memberCount": "41,000+ members", "description": "Production post-mortems, cluster security hardening guides, and Helm chart updates.", "joinUrl": "https://t.me/kubernetes", "tags": ["kubernetes", "containers", "telegram"]},
        {"title": "DevOps Weekly Broadcast", "platform": "Telegram", "category": "DevOps News", "memberCount": "55,000+ members", "description": "Curated telemetry, infrastructure-as-code snippets, and site reliability incident summaries.", "joinUrl": "https://t.me/devops", "tags": ["devops", "sre", "telegram"]},
        {"title": "Go Forum Bridge", "platform": "Forum", "category": "Go Discussions", "memberCount": "72,000+ members", "description": "The premier independent discussion forum for Go programmers seeking architectural guidance.", "joinUrl": "https://forum.golangbridge.org", "tags": ["golang", "forum", "community"]},
        {"title": "Kubernetes Discuss Forum", "platform": "Forum", "category": "Cloud Native Forum", "memberCount": "130,000+ members", "description": "Official community discussion board for Kubernetes cluster operators, SIG working groups, and plugin authors.", "joinUrl": "https://discuss.kubernetes.io", "tags": ["kubernetes", "k8s", "forum"]},
        {"title": "CNCF Community Platform", "platform": "Forum", "category": "Cloud Native Architecture", "memberCount": "190,000+ members", "description": "Global events, project roadmaps, and technical working group discussions across cloud-native tooling.", "joinUrl": "https://community.cncf.io", "tags": ["cncf", "cloudnative", "forum"]},
        {"title": "Official Go GitHub Repository", "platform": "GitHub", "category": "Go Source Code", "memberCount": "125,000+ stars", "description": "The official repository for the Go programming language, tracking language proposals, runtime issues, and PRs.", "joinUrl": "https://github.com/golang/go", "tags": ["golang", "github", "source"]}
    ],
    "growth_marketing": [
        {"title": "r/growthhacking Scaling Loops", "platform": "Reddit", "category": "Growth Hacking", "memberCount": "92,000+ members", "description": "Data-driven acquisition loops, cold email infrastructure, programmatic landing pages, and virality mechanics.", "joinUrl": "https://www.reddit.com/r/growthhacking/", "tags": ["growth", "marketing", "acquisition", "reddit"]},
        {"title": "r/SEO Search Optimization", "platform": "Reddit", "category": "Search Engine Optimization", "memberCount": "280,000+ members", "description": "Technical SEO audits, Core Web Vitals, link building strategies, and algorithmic Google update discussions.", "joinUrl": "https://www.reddit.com/r/SEO/", "tags": ["seo", "serp", "google", "reddit"]},
        {"title": "r/marketing Professional Strategists", "platform": "Reddit", "category": "General Marketing", "memberCount": "780,000+ members", "description": "Omnichannel brand positioning, customer lifetime value (LTV) modeling, and marketing mix modeling (MMM).", "joinUrl": "https://www.reddit.com/r/marketing/", "tags": ["marketing", "strategy", "brand", "reddit"]},
        {"title": "r/digitalmarketing Performance Media", "platform": "Reddit", "category": "Digital Media", "memberCount": "240,000+ members", "description": "Attribution modeling, programmatic media buying, conversion rate optimization (CRO), and ROAS analytics.", "joinUrl": "https://www.reddit.com/r/digitalmarketing/", "tags": ["digital", "performance", "analytics", "reddit"]},
        {"title": "r/PPC Paid Advertising", "platform": "Reddit", "category": "Paid Search & Social", "memberCount": "165,000+ members", "description": "Google Ads Performance Max campaigns, Meta ad account scaling, TikTok ads bidding, and negative keyword lists.", "joinUrl": "https://www.reddit.com/r/PPC/", "tags": ["ppc", "googleads", "metaads", "reddit"]},
        {"title": "r/content_marketing Content Strategy", "platform": "Reddit", "category": "Content Marketing", "memberCount": "135,000+ members", "description": "Hub-and-spoke topic clusters, editorial calendars, repurposing workflows, and authoritative thought leadership.", "joinUrl": "https://www.reddit.com/r/content_marketing/", "tags": ["content", "copywriting", "strategy", "reddit"]},
        {"title": "r/socialmediamarketing Social Growth", "platform": "Reddit", "category": "Social Media", "memberCount": "195,000+ members", "description": "Short-form video retention curves, LinkedIn personal branding frameworks, and community engagement tactics.", "joinUrl": "https://www.reddit.com/r/socialmediamarketing/", "tags": ["social", "video", "engagement", "reddit"]},
        {"title": "r/emailmarketing Retention & Deliverability", "platform": "Reddit", "category": "Email Marketing", "memberCount": "82,000+ members", "description": "DKIM/SPF/DMARC authentication, automated welcome drip flows, list segmentation, and open rate optimization.", "joinUrl": "https://www.reddit.com/r/emailmarketing/", "tags": ["email", "deliverability", "klaviyo", "reddit"]},
        {"title": "r/AffiliateMarketing Performance RevShare", "platform": "Reddit", "category": "Affiliate Marketing", "memberCount": "170,000+ members", "description": "CPA affiliate networks, high-intent review sites, disclosure compliance, and commission optimization.", "joinUrl": "https://www.reddit.com/r/AffiliateMarketing/", "tags": ["affiliate", "cpa", "revshare", "reddit"]},
        {"title": "r/copywriting Direct Response", "platform": "Reddit", "category": "Persuasive Copywriting", "memberCount": "210,000+ members", "description": "High-converting VSL scripts, long-form sales letters, hook formulas, and landing page psychology.", "joinUrl": "https://www.reddit.com/r/copywriting/", "tags": ["copywriting", "direct-response", "cro", "reddit"]},
        {"title": "r/bigseo Advanced Enterprise SEO", "platform": "Reddit", "category": "Enterprise SEO", "memberCount": "115,000+ members", "description": "Crawl budget management, hreflang multi-region matrices, JavaScript rendering, and log file analysis.", "joinUrl": "https://www.reddit.com/r/bigseo/", "tags": ["seo", "enterprise", "crawling", "reddit"]},
        {"title": "r/TechSEO Technical Audits", "platform": "Reddit", "category": "Technical SEO", "memberCount": "48,000+ members", "description": "Schema JSON-LD graph structures, canonical tags, server response headers, and indexation hygiene.", "joinUrl": "https://www.reddit.com/r/TechSEO/", "tags": ["techseo", "schema", "indexing", "reddit"]},
        {"title": "r/analytics Web Measurement", "platform": "Reddit", "category": "Data Analytics", "memberCount": "175,000+ members", "description": "Conversion funnels, BigQuery event export queries, cohort retention analysis, and A/B testing stats.", "joinUrl": "https://www.reddit.com/r/analytics/", "tags": ["analytics", "ga4", "data", "reddit"]},
        {"title": "r/GoogleAnalytics GA4 Tracking", "platform": "Reddit", "category": "Google Analytics", "memberCount": "42,000+ members", "description": "Custom event definitions, user property tracking, measurement protocol parameters, and Looker Studio reports.", "joinUrl": "https://www.reddit.com/r/GoogleAnalytics/", "tags": ["ga4", "tracking", "measurement", "reddit"]},
        {"title": "r/Entrepreneur Scaling Business", "platform": "Reddit", "category": "Business Growth", "memberCount": "3,100,000+ members", "description": "Founder masterminds discussing product-market fit, customer acquisition costs (CAC), and payback periods.", "joinUrl": "https://www.reddit.com/r/Entrepreneur/", "tags": ["entrepreneur", "growth", "business", "reddit"]},
        {"title": "Growth Hackers World Discord", "platform": "Discord", "category": "Growth Tactics", "memberCount": "45,000+ members", "description": "Live discussions on viral mechanics, programmatic SEO pipelines, and conversion rate optimizations.", "joinUrl": "https://discord.gg/growth", "tags": ["growth", "cro", "discord"]},
        {"title": "Marketing Professionals Discord", "platform": "Discord", "category": "Brand & Performance", "memberCount": "58,000+ members", "description": "Channels dedicated to SEO, Google Ads, Meta scaling, creative briefs, and CRO experimentation.", "joinUrl": "https://discord.gg/marketing", "tags": ["marketing", "advertising", "discord"]},
        {"title": "SEO & Webmaster Hub Discord", "platform": "Discord", "category": "Search Ranking", "memberCount": "38,000+ members", "description": "Discussions on SERP volatility, Google core updates, internal link matrices, and schema optimization.", "joinUrl": "https://discord.gg/seo", "tags": ["seo", "serp", "discord"]},
        {"title": "Affiliate & Media Buying Discord", "platform": "Discord", "category": "Paid Media & RevShare", "memberCount": "32,000+ members", "description": "Native advertising, push traffic, cloaking-free landing pages, and CPA network discussions.", "joinUrl": "https://discord.gg/affiliate", "tags": ["affiliate", "media-buying", "discord"]},
        {"title": "Digital Marketers Guild Discord", "platform": "Discord", "category": "Digital Agency", "memberCount": "44,000+ members", "description": "Agency owners discussing client retention, reporting templates, and omnichannel campaign structures.", "joinUrl": "https://discord.gg/digitalmarketing", "tags": ["agency", "marketing", "discord"]},
        {"title": "Startups & Growth Loops Discord", "platform": "Discord", "category": "Early Growth", "memberCount": "95,000+ members", "description": "Bootstrappers sharing cold outreach tactics, inbound flywheel setup, and product-led growth metrics.", "joinUrl": "https://discord.gg/startups", "tags": ["startups", "growth", "discord"]},
        {"title": "Growth Hacking Telegram Hub", "platform": "Telegram", "category": "Growth Loops", "memberCount": "38,000+ members", "description": "Daily case studies on SaaS onboarding funnels, referral program design, and virality coefficients.", "joinUrl": "https://t.me/growthhacking", "tags": ["growth", "saas", "telegram"]},
        {"title": "Digital Marketing Insights Telegram", "platform": "Telegram", "category": "Marketing News", "memberCount": "52,000+ members", "description": "Real-time updates on ad policy shifts, algorithm updates, and emerging advertising channels.", "joinUrl": "https://t.me/digitalmarketing", "tags": ["marketing", "news", "telegram"]},
        {"title": "SEO Signals Broadcast Telegram", "platform": "Telegram", "category": "Search Updates", "memberCount": "46,000+ members", "description": "Alerts on Google search quality rater guidelines updates and confirmed search ranking adjustments.", "joinUrl": "https://t.me/seo", "tags": ["seo", "google", "telegram"]},
        {"title": "Affiliate Marketing News Telegram", "platform": "Telegram", "category": "Affiliate Updates", "memberCount": "34,000+ members", "description": "High-converting offer alerts, vertical commission changes, and tracking platform updates.", "joinUrl": "https://t.me/affiliatemarketing", "tags": ["affiliate", "offers", "telegram"]},
        {"title": "GrowthHackers Community Forum", "platform": "Forum", "category": "Growth Case Studies", "memberCount": "190,000+ members", "description": "The official community founded by Sean Ellis featuring granular experiment logs and growth frameworks.", "joinUrl": "https://growthhackers.com/posts", "tags": ["growth", "experiments", "forum"]},
        {"title": "Moz Q&A Search Community", "platform": "Forum", "category": "SEO Best Practices", "memberCount": "140,000+ members", "description": "Authoritative search marketing advice on canonicalization, link equity, and algorithmic penalties.", "joinUrl": "https://moz.com/community/q", "tags": ["moz", "seo", "forum"]},
        {"title": "HubSpot Inbound Community", "platform": "Forum", "category": "Inbound & CRM", "memberCount": "220,000+ members", "description": "Marketing automation workflows, lead scoring criteria, and customer journey orchestration.", "joinUrl": "https://community.hubspot.com", "tags": ["hubspot", "inbound", "forum"]},
        {"title": "BlackHatWorld Digital Marketing", "platform": "Forum", "category": "Aggressive Marketing", "memberCount": "850,000+ members", "description": "High-volume traffic generation, scraping methodologies, proxy setups, and social media automation.", "joinUrl": "https://www.blackhatworld.com", "tags": ["traffic", "automation", "forum"]},
        {"title": "Product Hunt Discussion Guild", "platform": "Forum", "category": "Product Launches", "memberCount": "650,000+ members", "description": "Crowdsourced advice on launch-day promotion, influencer outreach, and press syndicate coverage.", "joinUrl": "https://www.producthunt.com/discussions", "tags": ["producthunt", "launches", "forum"]}
    ],
    "ui_ux_design": [
        {"title": "r/FigmaDesign Component Architecture", "platform": "Reddit", "category": "Figma & Design Systems", "memberCount": "130,000+ members", "description": "Auto-layout 5.0 constraints, variable modes, component properties, design tokens, and Figma plugins.", "joinUrl": "https://www.reddit.com/r/FigmaDesign/", "tags": ["figma", "design-systems", "components", "reddit"]},
        {"title": "r/UI_UX Interface Design", "platform": "Reddit", "category": "UI/UX Design", "memberCount": "140,000+ members", "description": "Visual hierarchy, micro-interactions, responsive grid systems, and high-fidelity interface wireframes.", "joinUrl": "https://www.reddit.com/r/UI_UX/", "tags": ["ui", "ux", "interface", "reddit"]},
        {"title": "r/userexperience Research & Strategy", "platform": "Reddit", "category": "User Experience", "memberCount": "210,000+ members", "description": "Usability testing protocols, journey mapping, cognitive heuristics, and user interview synthesis.", "joinUrl": "https://www.reddit.com/r/userexperience/", "tags": ["ux", "research", "usability", "reddit"]},
        {"title": "r/webdesign Visual Web Crafts", "platform": "Reddit", "category": "Web Design", "memberCount": "720,000+ members", "description": "Modern website layouts, CSS grid frameworks, typography pairings, and visual design trends.", "joinUrl": "https://www.reddit.com/r/webdesign/", "tags": ["webdesign", "css", "layout", "reddit"]},
        {"title": "r/interactiondesign Motion & Flows", "platform": "Reddit", "category": "Interaction Design", "memberCount": "48,000+ members", "description": "Affordances, state transitions, motion timing functions, and cognitive ergonomic patterns.", "joinUrl": "https://www.reddit.com/r/interactiondesign/", "tags": ["interaction", "motion", "ergonomics", "reddit"]},
        {"title": "r/graphic_design Visual Systems", "platform": "Reddit", "category": "Graphic Design", "memberCount": "1,600,000+ members", "description": "Brand identity guidelines, color theory, iconography sets, and editorial grid systems.", "joinUrl": "https://www.reddit.com/r/graphic_design/", "tags": ["graphic-design", "branding", "color", "reddit"]},
        {"title": "r/Design Creative Masterminds", "platform": "Reddit", "category": "General Design", "memberCount": "2,400,000+ members", "description": "Cross-disciplinary design philosophy, industrial minimalism, and timeless aesthetic execution.", "joinUrl": "https://www.reddit.com/r/Design/", "tags": ["design", "aesthetics", "reddit"]},
        {"title": "r/frontend Design Engineering", "platform": "Reddit", "category": "Design Implementation", "memberCount": "410,000+ members", "description": "Translating Figma specs into React/Tailwind code, responsive container queries, and CSS variables.", "joinUrl": "https://www.reddit.com/r/frontend/", "tags": ["frontend", "css", "react", "reddit"]},
        {"title": "r/css Cascading Style Sheets", "platform": "Reddit", "category": "CSS Architecture", "memberCount": "160,000+ members", "description": "Modern CSS features, subgrid, cascade layers (@layer), flexbox alignment, and animation keyframes.", "joinUrl": "https://www.reddit.com/r/css/", "tags": ["css", "styling", "web", "reddit"]},
        {"title": "r/typography Type & Font Systems", "platform": "Reddit", "category": "Typography", "memberCount": "95,000+ members", "description": "Variable fonts, optical sizing, baseline grids, modular scales, and international font legibility.", "joinUrl": "https://www.reddit.com/r/typography/", "tags": ["typography", "fonts", "legibility", "reddit"]},
        {"title": "r/accessibility Inclusive Design", "platform": "Reddit", "category": "Accessibility & A11y", "memberCount": "24,000+ members", "description": "WCAG 2.2 AA compliance, color contrast ratios, screen reader navigation, and keyboard focus states.", "joinUrl": "https://www.reddit.com/r/accessibility/", "tags": ["a11y", "wcag", "accessibility", "reddit"]},
        {"title": "r/ProductManagement Product Alignment", "platform": "Reddit", "category": "Product Strategy", "memberCount": "290,000+ members", "description": "Collaborative handoff between product managers and design leads, feature roadmaps, and PRD specs.", "joinUrl": "https://www.reddit.com/r/ProductManagement/", "tags": ["product", "strategy", "handoff", "reddit"]},
        {"title": "r/UXDesign Professional Practice", "platform": "Reddit", "category": "UX Careers", "memberCount": "180,000+ members", "description": "Design critiques, portfolio presentation strategies, design system ROI, and enterprise design governance.", "joinUrl": "https://www.reddit.com/r/UXDesign/", "tags": ["ux", "careers", "design-systems", "reddit"]},
        {"title": "r/DesignSystems Design Token Ops", "platform": "Reddit", "category": "Design Systems", "memberCount": "22,000+ members", "description": "Multi-brand design token synchronization, Figma-to-code pipelines (Style Dictionary), and versioning.", "joinUrl": "https://www.reddit.com/r/DesignSystems/", "tags": ["design-systems", "tokens", "architecture", "reddit"]},
        {"title": "r/UserExperienceDesign UX Crafts", "platform": "Reddit", "category": "UX Methodology", "memberCount": "65,000+ members", "description": "Card sorting experiments, tree testing, information architecture, and microcopy usability.", "joinUrl": "https://www.reddit.com/r/UserExperienceDesign/", "tags": ["ux", "architecture", "testing", "reddit"]},
        {"title": "Figma Community Discord", "platform": "Discord", "category": "Figma Builders", "memberCount": "85,000+ members", "description": "The primary Discord server for Figma power users, plugin developers, and widget creators.", "joinUrl": "https://discord.gg/figma", "tags": ["figma", "plugins", "discord"]},
        {"title": "Design Buddies Global Discord", "platform": "Discord", "category": "Design Community", "memberCount": "64,000+ members", "description": "Inclusive global design community hosting workshops, portfolio reviews, and design system events.", "joinUrl": "https://discord.gg/designbuddies", "tags": ["design", "portfolio", "discord"]},
        {"title": "UI/UX Designers Discord", "platform": "Discord", "category": "Interface Design", "memberCount": "52,000+ members", "description": "Critique channels, prototyping tips in ProtoPie and Figma, and accessibility discussions.", "joinUrl": "https://discord.gg/uiux", "tags": ["uiux", "prototyping", "discord"]},
        {"title": "Frontend & UI Engineering Discord", "platform": "Discord", "category": "Design to Code", "memberCount": "46,000+ members", "description": "Collaborative server bridging the gap between Figma design systems and React component libraries.", "joinUrl": "https://discord.gg/frontend", "tags": ["frontend", "react", "discord"]},
        {"title": "Web Design Mastermind Discord", "platform": "Discord", "category": "Web Aesthetics", "memberCount": "38,000+ members", "description": "Responsive layout design, typography scaling, 3D web graphics, and micro-interaction polish.", "joinUrl": "https://discord.gg/webdesign", "tags": ["webdesign", "layout", "discord"]},
        {"title": "Graphic Designers Lounge Discord", "platform": "Discord", "category": "Visual Identity", "memberCount": "41,000+ members", "description": "Branding projects, vector illustration critiques, color palettes, and typographic exploration.", "joinUrl": "https://discord.gg/graphicdesign", "tags": ["graphic-design", "branding", "discord"]},
        {"title": "Product Designers Club Discord", "platform": "Discord", "category": "Product UX", "memberCount": "35,000+ members", "description": "Enterprise product design discussions, user flow diagrams, and complex dashboard architectures.", "joinUrl": "https://discord.gg/productdesign", "tags": ["product-design", "enterprise", "discord"]},
        {"title": "UI/UX Designers Telegram", "platform": "Telegram", "category": "Design Inspiration", "memberCount": "58,000+ members", "description": "Daily UI animation reels, component breakdown case studies, and design system updates.", "joinUrl": "https://t.me/uiux", "tags": ["uiux", "inspiration", "telegram"]},
        {"title": "Figma Power Users Telegram", "platform": "Telegram", "category": "Figma News", "memberCount": "44,000+ members", "description": "Figma feature updates, community UI kits, shortcuts, and component library tutorials.", "joinUrl": "https://t.me/figma", "tags": ["figma", "tutorials", "telegram"]},
        {"title": "Web Design Trends Telegram", "platform": "Telegram", "category": "Web Design News", "memberCount": "36,000+ members", "description": "Curated modern websites, award-winning CSS interactions, and visual layout breakdowns.", "joinUrl": "https://t.me/webdesign", "tags": ["webdesign", "trends", "telegram"]},
        {"title": "Mobile UI Patterns Telegram", "platform": "Telegram", "category": "Mobile Design", "memberCount": "32,000+ members", "description": "iOS Human Interface Guidelines, Material 3 specs, and tactile mobile micro-interactions.", "joinUrl": "https://t.me/mobileui", "tags": ["mobile", "ios", "telegram"]},
        {"title": "Figma Official Forum", "platform": "Forum", "category": "Design Tool Forum", "memberCount": "220,000+ members", "description": "Official forum for feature requests, bug reports, API development, and design token integration.", "joinUrl": "https://forum.figma.com", "tags": ["figma", "official", "forum"]},
        {"title": "Designer News Collective", "platform": "Forum", "category": "Design News", "memberCount": "85,000+ members", "description": "Community-curated news on product launches, typography trends, and design industry insights.", "joinUrl": "https://www.designernews.co", "tags": ["designernews", "curation", "forum"]},
        {"title": "Dribbble Design Stories", "platform": "Forum", "category": "Visual Portfolio", "memberCount": "950,000+ members", "description": "In-depth articles and discussions on branding case studies, animation breakdowns, and interface polish.", "joinUrl": "https://dribbble.com/stories", "tags": ["dribbble", "stories", "forum"]},
        {"title": "Behance Curated Galleries", "platform": "Forum", "category": "Creative Showcase", "memberCount": "1,200,000+ members", "description": "World-class graphic design, typography showcase, brand identity systems, and UI case studies.", "joinUrl": "https://www.behance.net/galleries", "tags": ["behance", "galleries", "forum"]}
    ],
    "music_production_audio": [
        {"title": "r/edmproduction Electronic Producers", "platform": "Reddit", "category": "Music Production", "memberCount": "390,000+ members", "description": "Synthesis design, sidechain compression, EQ separation, sub-bass mixdown, and mastering plugins.", "joinUrl": "https://www.reddit.com/r/edmproduction/", "tags": ["edm", "synthesis", "mixing", "reddit"]},
        {"title": "r/synthesizers Hardware & Modular", "platform": "Reddit", "category": "Synthesizers", "memberCount": "280,000+ members", "description": "Analog modular Eurorack gear, polyphonic synthesizers, patch routing, and sound design techniques.", "joinUrl": "https://www.reddit.com/r/synthesizers/", "tags": ["synths", "modular", "analog", "reddit"]},
        {"title": "r/WeAreTheMusicMakers Audio Hub", "platform": "Reddit", "category": "Music Creators", "memberCount": "2,400,000+ members", "description": "Home studio acoustics, recording chains, audio interface impedance, and creative songwriting.", "joinUrl": "https://www.reddit.com/r/WeAreTheMusicMakers/", "tags": ["music", "studio", "recording", "reddit"]},
        {"title": "r/audioengineering Studio Engineering", "platform": "Reddit", "category": "Audio Engineering", "memberCount": "320,000+ members", "description": "Acoustic treatment, reference monitors, gain staging, dynamic range, and analog console modeling.", "joinUrl": "https://www.reddit.com/r/audioengineering/", "tags": ["audio", "engineering", "mastering", "reddit"]},
        {"title": "r/ableton Live Workflows", "platform": "Reddit", "category": "Ableton Live", "memberCount": "240,000+ members", "description": "Ableton Live 12 racks, Max for Live devices, audio warping algorithms, and MIDI routing.", "joinUrl": "https://www.reddit.com/r/ableton/", "tags": ["ableton", "daw", "midi", "reddit"]},
        {"title": "r/FL_Studio Image-Line Guild", "platform": "Reddit", "category": "FL Studio", "memberCount": "310,000+ members", "description": "Fruity Loops piano roll automation, stock synth modulation (Sytrus/Harmor), and mixer routing.", "joinUrl": "https://www.reddit.com/r/FL_Studio/", "tags": ["flstudio", "daw", "beats", "reddit"]},
        {"title": "r/Logic_Studio Apple DAW Hub", "platform": "Reddit", "category": "Logic Pro", "memberCount": "95,000+ members", "description": "Logic Pro spatial audio mixing, Alchemy synthesizer soundscapes, and stock compressor models.", "joinUrl": "https://www.reddit.com/r/Logic_Studio/", "tags": ["logic", "apple", "daw", "reddit"]},
        {"title": "r/modular Eurorack Systems", "platform": "Reddit", "category": "Modular Synthesizers", "memberCount": "85,000+ members", "description": "Control voltage (CV) modulation, clock dividers, granulators, and custom Eurorack case design.", "joinUrl": "https://www.reddit.com/r/modular/", "tags": ["modular", "eurorack", "cv", "reddit"]},
        {"title": "r/makinghiphop Beat Production", "platform": "Reddit", "category": "Beatmaking & Sampling", "memberCount": "190,000+ members", "description": "Vinyl sample chopping, MPC swing grooves, 808 distortion, and drum pattern layering.", "joinUrl": "https://www.reddit.com/r/makinghiphop/", "tags": ["hiphop", "beats", "sampling", "reddit"]},
        {"title": "r/sounddesign Audio Synthesis", "platform": "Reddit", "category": "Sound Design", "memberCount": "62,000+ members", "description": "Foley recording, sci-fi synth impacts, cinematic risers, and frequency modulation techniques.", "joinUrl": "https://www.reddit.com/r/sounddesign/", "tags": ["sound-design", "foley", "cinematic", "reddit"]},
        {"title": "r/mixingmastering Mix Engineers", "platform": "Reddit", "category": "Mixing & Mastering", "memberCount": "88,000+ members", "description": "LUFS loudness standards, stereo width correlation, multiband saturation, and clipping algorithms.", "joinUrl": "https://www.reddit.com/r/mixingmastering/", "tags": ["mixing", "mastering", "lufs", "reddit"]},
        {"title": "r/trapproduction Modern Urban Production", "platform": "Reddit", "category": "Trap & Hip Hop", "memberCount": "140,000+ members", "description": "Glide 808s, hi-hat roll velocity randomization, melody loops, and sub-bass saturation.", "joinUrl": "https://www.reddit.com/r/trapproduction/", "tags": ["trap", "808", "production", "reddit"]},
        {"title": "r/Reaper Cockos DAW", "platform": "Reddit", "category": "Reaper DAW", "memberCount": "82,000+ members", "description": "Custom JSFX scripts, customized action hotkeys, lightweight performance, and routing flexibility.", "joinUrl": "https://www.reddit.com/r/Reaper/", "tags": ["reaper", "daw", "scripts", "reddit"]},
        {"title": "r/Bitwig Next-Gen DAW", "platform": "Reddit", "category": "Bitwig Studio", "memberCount": "26,000+ members", "description": "Bitwig The Grid modular synthesis, polyphonic expression (MPE), and unified modulation.", "joinUrl": "https://www.reddit.com/r/Bitwig/", "tags": ["bitwig", "mpe", "daw", "reddit"]},
        {"title": "r/audiophile High-Fidelity Audio", "platform": "Reddit", "category": "High-Fidelity Audio", "memberCount": "1,100,000+ members", "description": "DAC convertors, planar magnetic headphones, room acoustic treatment, and transparent amplification.", "joinUrl": "https://www.reddit.com/r/audiophile/", "tags": ["audiophile", "hifi", "headphones", "reddit"]},
        {"title": "Music Production Global Discord", "platform": "Discord", "category": "Audio Production", "memberCount": "72,000+ members", "description": "Active Discord for producers sharing feedback, sample libraries, and plugin recommendations.", "joinUrl": "https://discord.gg/musicproduction", "tags": ["music", "production", "discord"]},
        {"title": "Ableton Producers Guild Discord", "platform": "Discord", "category": "Ableton Live", "memberCount": "58,000+ members", "description": "Live production streams, project file exchanges, and Max for Live troubleshooting.", "joinUrl": "https://discord.gg/ableton", "tags": ["ableton", "daw", "discord"]},
        {"title": "FL Studio Official Discord", "platform": "Discord", "category": "FL Studio", "memberCount": "65,000+ members", "description": "Beat battles, vocal mixing channels, stock plugin challenges, and pattern automation tutorials.", "joinUrl": "https://discord.gg/flstudio", "tags": ["flstudio", "beats", "discord"]},
        {"title": "Modular Synth Enthusiasts Discord", "platform": "Discord", "category": "Hardware & Eurorack", "memberCount": "32,000+ members", "description": "Patch notes, DIY module soldering, oscillator comparisons, and generative ambient streams.", "joinUrl": "https://discord.gg/modular", "tags": ["modular", "synths", "discord"]},
        {"title": "Audio Engineering Collective Discord", "platform": "Discord", "category": "Mix & Master", "memberCount": "44,000+ members", "description": "Mix critique channels, reference track comparisons, and monitoring acoustic discussions.", "joinUrl": "https://discord.gg/audioengineering", "tags": ["audio", "mastering", "discord"]},
        {"title": "EDM Producers Hub Discord", "platform": "Discord", "category": "Electronic Dance Music", "memberCount": "51,000+ members", "description": "Genre-specific channels for house, techno, bass music, synthwave, and trance production.", "joinUrl": "https://discord.gg/edmproduction", "tags": ["edm", "electronic", "discord"]},
        {"title": "Beatmakers Lounge Discord", "platform": "Discord", "category": "Hip Hop & Beats", "memberCount": "38,000+ members", "description": "Producer cookups, vinyl digging discussions, loop sharing, and vocal engineering tips.", "joinUrl": "https://discord.gg/makinghiphop", "tags": ["hiphop", "beats", "discord"]},
        {"title": "Music Producers Daily Telegram", "platform": "Telegram", "category": "Producer News", "memberCount": "48,000+ members", "description": "Free plugin alerts, VST discount announcements, and high-quality sound pack drops.", "joinUrl": "https://t.me/musicproduction", "tags": ["music", "vst", "telegram"]},
        {"title": "Sound Design Masters Telegram", "platform": "Telegram", "category": "Synthesis News", "memberCount": "35,000+ members", "description": "Serum and Vital presets, wavetable distributions, and cinematic foley sample links.", "joinUrl": "https://t.me/sounddesign", "tags": ["sound-design", "presets", "telegram"]},
        {"title": "Ableton Workflow Telegram", "platform": "Telegram", "category": "DAW Tips", "memberCount": "28,000+ members", "description": "Quick keyboard shortcut tips, audio rack downloads, and mixing chain walkthroughs.", "joinUrl": "https://t.me/ableton", "tags": ["ableton", "tips", "telegram"]},
        {"title": "FL Studio Power Users Telegram", "platform": "Telegram", "category": "Beatmaking Tips", "memberCount": "31,000+ members", "description": "MIDI chord progression packs, mixer routing presets, and beat production walkthroughs.", "joinUrl": "https://t.me/flstudio", "tags": ["flstudio", "tips", "telegram"]},
        {"title": "Gearspace Pro Audio Forum", "platform": "Forum", "category": "High-End Audio", "memberCount": "420,000+ members", "description": "The authoritative industry forum for microphone shootouts, outboard gear reviews, and mixing debates.", "joinUrl": "https://gearspace.com/board/", "tags": ["gearspace", "hardware", "forum"]},
        {"title": "KVR Audio VST Forum", "platform": "Forum", "category": "Virtual Instruments", "memberCount": "310,000+ members", "description": "The largest database and discussion forum for software synthesizers, audio effects, and DSP plugins.", "joinUrl": "https://www.kvraudio.com/forum/", "tags": ["kvr", "vst", "forum"]},
        {"title": "Mod Wiggler Modular Forum", "platform": "Forum", "category": "Modular Synthesizers", "memberCount": "180,000+ members", "description": "The definitive global community for Eurorack modular synthesizers, patch sharing, and DIY circuits.", "joinUrl": "https://www.modwiggler.com/forum/", "tags": ["modular", "eurorack", "forum"]},
        {"title": "Sound On Sound Official Forum", "platform": "Forum", "category": "Music Tech & Recording", "memberCount": "260,000+ members", "description": "Veteran audio engineers discussing acoustic treatment, microphone techniques, and monitoring fidelity.", "joinUrl": "https://www.soundonsound.com/forum", "tags": ["sos", "recording", "forum"]}
    ],
    "fire_movement": [
        {"title": "r/financialindependence FIRE Hub", "platform": "Reddit", "category": "Financial Independence", "memberCount": "2,200,000+ members", "description": "The premier global community for calculating safe withdrawal rates, maximizing savings rates, and achieving early retirement.", "joinUrl": "https://www.reddit.com/r/financialindependence/", "tags": ["fire", "retirement", "investing", "reddit"]},
        {"title": "r/leanfire Minimalist FIRE", "platform": "Reddit", "category": "Lean FIRE", "memberCount": "290,000+ members", "description": "Strategies for achieving financial independence on an annual budget under $40,000 through extreme frugality.", "joinUrl": "https://www.reddit.com/r/leanfire/", "tags": ["leanfire", "frugality", "budgeting", "reddit"]},
        {"title": "r/fatFIRE High-Net-Worth FIRE", "platform": "Reddit", "category": "Fat FIRE", "memberCount": "420,000+ members", "description": "Achieving early retirement with high expenditure ($100k-$500k+/year), estate planning, and private equity investments.", "joinUrl": "https://www.reddit.com/r/fatFIRE/", "tags": ["fatfire", "wealth", "investing", "reddit"]},
        {"title": "r/Bogleheads Passive Indexing", "platform": "Reddit", "category": "Index Funds", "memberCount": "390,000+ members", "description": "The legendary 3-fund portfolio (VTI/VXUS/BND), low-cost indexing, and buy-and-hold investing philosophy.", "joinUrl": "https://www.reddit.com/r/Bogleheads/", "tags": ["bogleheads", "indexing", "vanguard", "reddit"]},
        {"title": "r/personalfinance Money Management", "platform": "Reddit", "category": "Personal Finance", "memberCount": "19,000,000+ members", "description": "Foundational money management, debt reduction waterfall, emergency funds, and 401(k) retirement matching.", "joinUrl": "https://www.reddit.com/r/personalfinance/", "tags": ["finance", "money", "budgeting", "reddit"]},
        {"title": "r/dividends Cash Flow Compounding", "platform": "Reddit", "category": "Dividend Growth", "memberCount": "620,000+ members", "description": "Building sustainable passive income through qualified dividend growth stocks, SCHD, and DRIP compounding.", "joinUrl": "https://www.reddit.com/r/dividends/", "tags": ["dividends", "passive-income", "stocks", "reddit"]},
        {"title": "r/investing Market Intelligence", "platform": "Reddit", "category": "Broad Market", "memberCount": "2,400,000+ members", "description": "Macroeconomic interest rates, treasury yield curves, index performance, and long-term equity valuation.", "joinUrl": "https://www.reddit.com/r/investing/", "tags": ["investing", "macro", "equities", "reddit"]},
        {"title": "r/stocks Equity Research", "platform": "Reddit", "category": "Stock Market", "memberCount": "6,500,000+ members", "description": "Quarterly earnings reports, corporate balance sheet analysis, valuation multiples, and market sentiment.", "joinUrl": "https://www.reddit.com/r/stocks/", "tags": ["stocks", "earnings", "valuation", "reddit"]},
        {"title": "r/FIREyFemmes Women in FIRE", "platform": "Reddit", "category": "Women & FIRE", "memberCount": "55,000+ members", "description": "Supportive community for women pursuing financial independence, salary negotiation, and wealth accumulation.", "joinUrl": "https://www.reddit.com/r/FIREyFemmes/", "tags": ["women", "fire", "careers", "reddit"]},
        {"title": "r/ChubbyFIRE Mid-Tier FIRE", "platform": "Reddit", "category": "Chubby FIRE", "memberCount": "72,000+ members", "description": "Planning for retirement with a net worth between $2.5M and $5M, balancing comfort without extreme excess.", "joinUrl": "https://www.reddit.com/r/ChubbyFIRE/", "tags": ["chubbyfire", "retirement", "investing", "reddit"]},
        {"title": "r/CoastFIRE Work-Life Balance", "platform": "Reddit", "category": "Coast FIRE", "memberCount": "110,000+ members", "description": "Investing aggressively early so compound growth covers retirement, freeing time for enjoyable part-time work.", "joinUrl": "https://www.reddit.com/r/CoastFIRE/", "tags": ["coastfire", "lifestyle", "compounding", "reddit"]},
        {"title": "r/PovertyFinance Financial Resilience", "platform": "Reddit", "category": "Financial Recovery", "memberCount": "2,100,000+ members", "description": "Practical guidance on credit score rehabilitation, frugal grocery hacks, and breaking the debt cycle.", "joinUrl": "https://www.reddit.com/r/PovertyFinance/", "tags": ["frugal", "debt", "recovery", "reddit"]},
        {"title": "r/realestateinvesting Cashflow Properties", "platform": "Reddit", "category": "Real Estate", "memberCount": "620,000+ members", "description": "Rental property cap rates, cash-on-cash returns, 1031 tax deferrals, and passive syndications.", "joinUrl": "https://www.reddit.com/r/realestateinvesting/", "tags": ["realestate", "cashflow", "investing", "reddit"]},
        {"title": "r/ValueInvesting Fundamental Analysis", "platform": "Reddit", "category": "Value Investing", "memberCount": "210,000+ members", "description": "Warren Buffett & Benjamin Graham value methodology, discounted cash flow (DCF), and margin of safety.", "joinUrl": "https://www.reddit.com/r/ValueInvesting/", "tags": ["value", "buffett", "dcf", "reddit"]},
        {"title": "r/passive_income Automated Cashflow", "platform": "Reddit", "category": "Passive Income", "memberCount": "480,000+ members", "description": "Comparing digital assets, real estate equity, high-yield dividend funds, and automated royalty models.", "joinUrl": "https://www.reddit.com/r/passive_income/", "tags": ["passive", "cashflow", "income", "reddit"]},
        {"title": "Financial Independence Global Discord", "platform": "Discord", "category": "FIRE Movement", "memberCount": "48,000+ members", "description": "Active community calculating net worth milestones, withdrawal simulations, and tax optimization.", "joinUrl": "https://discord.gg/fire", "tags": ["fire", "retirement", "discord"]},
        {"title": "Personal Finance Mastermind Discord", "platform": "Discord", "category": "Budget & Investing", "memberCount": "65,000+ members", "description": "Channels dedicated to budgeting tools, 401(k) allocations, tax minimization, and savings automation.", "joinUrl": "https://discord.gg/personalfinance", "tags": ["finance", "budget", "discord"]},
        {"title": "Dividends & Cashflow Discord", "platform": "Discord", "category": "Dividend Stocks", "memberCount": "38,000+ members", "description": "Discussion on dividend aristocrats, monthly income funds, and compounding dividend reinvestment.", "joinUrl": "https://discord.gg/dividends", "tags": ["dividends", "stocks", "discord"]},
        {"title": "Bogleheads Investors Discord", "platform": "Discord", "category": "Passive Investing", "memberCount": "32,000+ members", "description": "Strict adherence to Jack Bogle's simple, low-cost broad index fund philosophy.", "joinUrl": "https://discord.gg/bogleheads", "tags": ["bogleheads", "index", "discord"]},
        {"title": "Investing & Wealth Discord", "platform": "Discord", "category": "Equities & Macro", "memberCount": "72,000+ members", "description": "Macroeconomic market news, Federal Reserve rate decisions, and long-term asset allocation models.", "joinUrl": "https://discord.gg/investing", "tags": ["investing", "wealth", "discord"]},
        {"title": "Real Estate Investors Discord", "platform": "Discord", "category": "Property Investment", "memberCount": "41,000+ members", "description": "Underwriting residential multi-family units, BRRRR renovations, and tenant management workflows.", "joinUrl": "https://discord.gg/realestate", "tags": ["realestate", "properties", "discord"]},
        {"title": "FIRE Movement Telegram", "platform": "Telegram", "category": "FIRE Insights", "memberCount": "34,000+ members", "description": "Daily articles on geo-arbitrage, healthcare in early retirement, and asset drawdown strategies.", "joinUrl": "https://t.me/financialindependence", "tags": ["fire", "retirement", "telegram"]},
        {"title": "Personal Finance Tips Telegram", "platform": "Telegram", "category": "Money Management", "memberCount": "52,000+ members", "description": "Tax deadline reminders, savings interest rate updates, and practical money management tips.", "joinUrl": "https://t.me/personalfinance", "tags": ["finance", "savings", "telegram"]},
        {"title": "Dividend Investors Telegram", "platform": "Telegram", "category": "Dividend News", "memberCount": "29,000+ members", "description": "Quarterly dividend increase announcements, ex-dividend date calendars, and yield rankings.", "joinUrl": "https://t.me/dividendinvestors", "tags": ["dividends", "yield", "telegram"]},
        {"title": "Value Investing Hub Telegram", "platform": "Telegram", "category": "Fundamental Analysis", "memberCount": "24,000+ members", "description": "Annual report highlights, insider transaction filings, and margin-of-safety stock write-ups.", "joinUrl": "https://t.me/valueinvesting", "tags": ["value", "investing", "telegram"]},
        {"title": "Bogleheads Official Forum", "platform": "Forum", "category": "Bogleheads Collective", "memberCount": "280,000+ members", "description": "The gold standard of investor forums discussing asset allocation, tax-efficient fund placement, and safe withdrawals.", "joinUrl": "https://www.bogleheads.org/forum/", "tags": ["bogleheads", "investing", "forum"]},
        {"title": "Early Retirement Forum", "platform": "Forum", "category": "Early Retirement", "memberCount": "160,000+ members", "description": "Long-running forum where early retirees share actual budget telemetry, ACA healthcare navigation, and lifestyle tips.", "joinUrl": "https://www.early-retirement.org/forums/", "tags": ["early-retirement", "fire", "forum"]},
        {"title": "BiggerPockets Real Estate Forum", "platform": "Forum", "category": "Real Estate Wealth", "memberCount": "2,400,000+ members", "description": "Real estate investing deal analysis, private money lending, short-term rental management, and tax loopholes.", "joinUrl": "https://www.biggerpockets.com/forums", "tags": ["biggerpockets", "realestate", "forum"]},
        {"title": "Mr. Money Mustache Forum", "platform": "Forum", "category": "Badassity & Frugality", "memberCount": "190,000+ members", "description": "Classic forum dedicated to eliminating financial waste, DIY home repairs, biking, and hyper-early retirement.", "joinUrl": "https://forum.mrmoneymustache.com", "tags": ["mmm", "frugal", "forum"]},
        {"title": "ChooseFI Global Community", "platform": "Forum", "category": "FI Education", "memberCount": "140,000+ members", "description": "Local chapters, travel rewards credit card hacking, and career acceleration for financial independence.", "joinUrl": "https://www.choosefi.com/community/", "tags": ["choosefi", "community", "forum"]}
    ],
    "virtual_assistants": [
        {"title": "r/virtualassistant Global Hub", "platform": "Reddit", "category": "Virtual Assistance", "memberCount": "54,000+ members", "description": "Connecting founders and executive virtual assistants for executive calendar, inbox triage, and CRM admin.", "joinUrl": "https://www.reddit.com/r/virtualassistant/", "tags": ["va", "virtual-assistant", "admin", "reddit"]},
        {"title": "r/VirtualAssistantJobs Remote Contracts", "platform": "Reddit", "category": "VA Job Board", "memberCount": "32,000+ members", "description": "Verified remote job listings, client matchmaking, hourly rate standards, and contract templates.", "joinUrl": "https://www.reddit.com/r/VirtualAssistantJobs/", "tags": ["jobs", "hiring", "contracts", "reddit"]},
        {"title": "r/remotework Telecommuting & Culture", "platform": "Reddit", "category": "Remote Work", "memberCount": "190,000+ members", "description": "Remote team communication frameworks, async Loom management, time tracking software, and ergonomics.", "joinUrl": "https://www.reddit.com/r/remotework/", "tags": ["remotework", "telework", "async", "reddit"]},
        {"title": "r/freelance Independent Contractors", "platform": "Reddit", "category": "Freelance Operations", "memberCount": "410,000+ members", "description": "Client management, scope creep prevention, upfront deposit policies, and invoicing infrastructure.", "joinUrl": "https://www.reddit.com/r/freelance/", "tags": ["freelance", "contracts", "clients", "reddit"]},
        {"title": "r/Upwork Marketplace Mastery", "platform": "Reddit", "category": "Upwork Platform", "memberCount": "180,000+ members", "description": "Top Rated Plus badge acquisition, proposal optimization, Connects management, and payment dispute mediation.", "joinUrl": "https://www.reddit.com/r/Upwork/", "tags": ["upwork", "proposals", "talent", "reddit"]},
        {"title": "r/digitalnomad Location Independence", "platform": "Reddit", "category": "Digital Nomad", "memberCount": "2,400,000+ members", "description": "Managing overseas teams while working remotely, global co-working spaces, and reliable portable Wi-Fi.", "joinUrl": "https://www.reddit.com/r/digitalnomad/", "tags": ["nomad", "travel", "remote", "reddit"]},
        {"title": "r/WorkOnline Remote Employment", "platform": "Reddit", "category": "Online Careers", "memberCount": "620,000+ members", "description": "Vetted online customer support roles, data annotation, transcription, and remote admin opportunities.", "joinUrl": "https://www.reddit.com/r/WorkOnline/", "tags": ["workonline", "jobs", "careers", "reddit"]},
        {"title": "r/Entrepreneur Operational Scaling", "platform": "Reddit", "category": "Business Scaling", "memberCount": "3,100,000+ members", "description": "Founders building delegation frameworks, SOP libraries, and outsourcing back-office workflows.", "joinUrl": "https://www.reddit.com/r/Entrepreneur/", "tags": ["entrepreneur", "outsourcing", "delegation", "reddit"]},
        {"title": "r/smallbusiness Back-Office Operations", "platform": "Reddit", "category": "Small Business", "memberCount": "1,400,000+ members", "description": "Bookkeeping delegation, customer service desk coverage, and automated client appointment scheduling.", "joinUrl": "https://www.reddit.com/r/smallbusiness/", "tags": ["smallbiz", "operations", "delegation", "reddit"]},
        {"title": "r/Outsourcing Global Workforce", "platform": "Reddit", "category": "Offshore Staffing", "memberCount": "21,000+ members", "description": "Building offshore operational pods in the Philippines, Colombia, and Eastern Europe with proper payroll.", "joinUrl": "https://www.reddit.com/r/Outsourcing/", "tags": ["outsourcing", "offshore", "staffing", "reddit"]},
        {"title": "r/telework Remote Practices", "platform": "Reddit", "category": "Telework Practices", "memberCount": "15,000+ members", "description": "Asynchronous team standups, Slack channel etiquette, and home office productivity habits.", "joinUrl": "https://www.reddit.com/r/telework/", "tags": ["telework", "async", "habits", "reddit"]},
        {"title": "r/forhire Talent Marketplace", "platform": "Reddit", "category": "Talent Exchange", "memberCount": "340,000+ members", "description": "Direct marketplace connecting business owners with specialized virtual assistants and project specialists.", "joinUrl": "https://www.reddit.com/r/forhire/", "tags": ["forhire", "talent", "marketplace", "reddit"]},
        {"title": "r/Fiverr Gig Economy", "platform": "Reddit", "category": "Fiverr Gigs", "memberCount": "110,000+ members", "description": "Fiverr Pro gig ranking, customer review management, and handling buyer revision requests.", "joinUrl": "https://www.reddit.com/r/Fiverr/", "tags": ["fiverr", "gigs", "freelance", "reddit"]},
        {"title": "r/productivity Workflow Optimization", "platform": "Reddit", "category": "Executive Productivity", "memberCount": "2,800,000+ members", "description": "Time-blocking, Notion task managers, email inbox zero rules, and personal executive assistance.", "joinUrl": "https://www.reddit.com/r/productivity/", "tags": ["productivity", "inboxzero", "habits", "reddit"]},
        {"title": "r/RemoteJobs Verified Listings", "platform": "Reddit", "category": "Remote Hiring", "memberCount": "85,000+ members", "description": "Legitimate worldwide remote job vacancies for administrative assistants and customer support reps.", "joinUrl": "https://www.reddit.com/r/RemoteJobs/", "tags": ["remotejobs", "hiring", "reddit"]},
        {"title": "Virtual Assistants Global Discord", "platform": "Discord", "category": "VA Community", "memberCount": "34,000+ members", "description": "Active Discord for VAs sharing client management tips, rate cards, and software tool recommendations.", "joinUrl": "https://discord.gg/virtualassistants", "tags": ["va", "freelance", "discord"]},
        {"title": "Remote Workers Guild Discord", "platform": "Discord", "category": "Telework Support", "memberCount": "48,000+ members", "description": "Coworking pomodoro voice rooms, home office setup discussions, and global time zone management.", "joinUrl": "https://discord.gg/remotework", "tags": ["remotework", "coworking", "discord"]},
        {"title": "Freelancers Collective Discord", "platform": "Discord", "category": "Contractors", "memberCount": "52,000+ members", "description": "Proposal reviews, pricing negotiation strategies, and international wire transfer payment advice.", "joinUrl": "https://discord.gg/freelance", "tags": ["freelance", "rates", "discord"]},
        {"title": "Upwork & Freelance Pros Discord", "platform": "Discord", "category": "Platform Freelancing", "memberCount": "28,000+ members", "description": "Mastering Upwork profile search algorithms, client interview preparation, and project reviews.", "joinUrl": "https://discord.gg/upwork", "tags": ["upwork", "gigs", "discord"]},
        {"title": "Digital Nomads Lounge Discord", "platform": "Discord", "category": "Nomad Life", "memberCount": "62,000+ members", "description": "Co-living reviews, high-speed Wi-Fi speeds across nomad hubs, and travel health insurance.", "joinUrl": "https://discord.gg/nomads", "tags": ["nomads", "travel", "discord"]},
        {"title": "Founders & Operations Discord", "platform": "Discord", "category": "Operations Leadership", "memberCount": "75,000+ members", "description": "Business operators discussing SOP builders, Loom training libraries, and VA KPI tracking.", "joinUrl": "https://discord.gg/entrepreneur", "tags": ["operations", "delegation", "discord"]},
        {"title": "Virtual Assistants Hub Telegram", "platform": "Telegram", "category": "VA Job Alerts", "memberCount": "36,000+ members", "description": "Verified remote virtual assistant job postings, contract gigs, and client onboarding templates.", "joinUrl": "https://t.me/virtualassistants", "tags": ["va", "jobs", "telegram"]},
        {"title": "Remote Workers Broadcast Telegram", "platform": "Telegram", "category": "Remote Careers", "memberCount": "45,000+ members", "description": "Daily remote employment leads, async work culture articles, and home office ergonomics.", "joinUrl": "https://t.me/remotework", "tags": ["remotework", "careers", "telegram"]},
        {"title": "Freelance Gigs Telegram", "platform": "Telegram", "category": "Contracting Leads", "memberCount": "41,000+ members", "description": "Direct contractor leads for content writing, admin assistance, graphic design, and research.", "joinUrl": "https://t.me/freelance", "tags": ["freelance", "leads", "telegram"]},
        {"title": "Digital Nomad Network Telegram", "platform": "Telegram", "category": "Nomad Intel", "memberCount": "54,000+ members", "description": "Digital nomad visa updates, tax residency rules, and flight deal notifications.", "joinUrl": "https://t.me/digitalnomads", "tags": ["nomad", "visas", "telegram"]},
        {"title": "Upwork Community Forum", "platform": "Forum", "category": "Platform Discussions", "memberCount": "320,000+ members", "description": "Official forum for Upwork freelancers and clients discussing contract terms, payments, and badges.", "joinUrl": "https://community.upwork.com", "tags": ["upwork", "official", "forum"]},
        {"title": "Fiverr Community Forum", "platform": "Forum", "category": "Gig Optimization", "memberCount": "240,000+ members", "description": "Official community discussing gig impression metrics, seller level upgrades, and buyer requests.", "joinUrl": "https://community.fiverr.com", "tags": ["fiverr", "gigs", "forum"]},
        {"title": "Nomad List Community Hub", "platform": "Forum", "category": "Global Living", "memberCount": "110,000+ members", "description": "Global database and discussion platform ranking cities by Wi-Fi speed, cost of living, and safety.", "joinUrl": "https://nomadlist.com", "tags": ["nomadlist", "travel", "forum"]},
        {"title": "OnlineJobs.ph Employer Guide", "platform": "Forum", "category": "Philippines Staffing", "memberCount": "190,000+ members", "description": "Authoritative guide and advice on hiring, interviewing, and managing virtual assistants from the Philippines.", "joinUrl": "https://www.onlinejobs.ph/blog/", "tags": ["philippines", "staffing", "forum"]},
        {"title": "Freelancers Union Community", "platform": "Forum", "category": "Contractor Advocacy", "memberCount": "500,000+ members", "description": "Nonprofit community offering contract templates, healthcare resources, and legal support for independent workers.", "joinUrl": "https://www.freelancersunion.org", "tags": ["freelancersunion", "advocacy", "forum"]}
    ],
    "podcast_creators": [
        {"title": "r/podcasting Audio Creators", "platform": "Reddit", "category": "Podcast Production", "memberCount": "195,000+ members", "description": "Microphone technique (Shure SM7B), audio interfaces, acoustic room treatment, and RSS feed distribution.", "joinUrl": "https://www.reddit.com/r/podcasting/", "tags": ["podcasting", "audio", "microphones", "reddit"]},
        {"title": "r/podcasts Show Recommendations", "platform": "Reddit", "category": "Listener Network", "memberCount": "2,800,000+ members", "description": "Listener discussions, storytelling formats, audience reviews, and discovering breakout indie podcasts.", "joinUrl": "https://www.reddit.com/r/podcasts/", "tags": ["podcasts", "shows", "discovery", "reddit"]},
        {"title": "r/audioengineering Broadcast Audio", "platform": "Reddit", "category": "Audio Engineering", "memberCount": "320,000+ members", "description": "Loudness standards (-16 LUFS for stereo podcasts), vocal EQ de-essing, noise reduction, and compression.", "joinUrl": "https://www.reddit.com/r/audioengineering/", "tags": ["audio", "engineering", "lufs", "reddit"]},
        {"title": "r/audiodrama Audio Fiction", "platform": "Reddit", "category": "Audio Drama & Narrative", "memberCount": "140,000+ members", "description": "Fictional storytelling podcasts, binaural 3D audio design, voice cast directing, and narrative scoring.", "joinUrl": "https://www.reddit.com/r/audiodrama/", "tags": ["audiodrama", "fiction", "binaural", "reddit"]},
        {"title": "r/voiceacting Voice Over Artists", "platform": "Reddit", "category": "Voice Acting", "memberCount": "180,000+ members", "description": "Voiceover technique, commercial demo reels, home whisper rooms, and talent agency representation.", "joinUrl": "https://www.reddit.com/r/voiceacting/", "tags": ["voiceacting", "voiceover", "audio", "reddit"]},
        {"title": "r/microphones Vocal Capture", "platform": "Reddit", "category": "Microphone Tech", "memberCount": "42,000+ members", "description": "Dynamic vs condenser mics, polar pickup patterns, preamps, and pop filter isolation.", "joinUrl": "https://www.reddit.com/r/microphones/", "tags": ["microphones", "gear", "hardware", "reddit"]},
        {"title": "r/broadcastengineering Studio Broadcast", "platform": "Reddit", "category": "Broadcast Tech", "memberCount": "38,000+ members", "description": "Dante audio-over-IP, SDI video integration, broadcast consoles, and live stream telemetry.", "joinUrl": "https://www.reddit.com/r/broadcastengineering/", "tags": ["broadcast", "dante", "engineering", "reddit"]},
        {"title": "r/audiophile Sound Fidelity", "platform": "Reddit", "category": "Fidelity & Monitoring", "memberCount": "1,100,000+ members", "description": "High-end DAC monitoring, neutral studio reference headphones, and room frequency response calibration.", "joinUrl": "https://www.reddit.com/r/audiophile/", "tags": ["audiophile", "monitoring", "fidelity", "reddit"]},
        {"title": "r/YouTube_Startups Video Podcasting", "platform": "Reddit", "category": "Video Podcasts", "memberCount": "165,000+ members", "description": "Multi-camera studio setups, thumbnail optimization for video podcasts, and YouTube Shorts clips.", "joinUrl": "https://www.reddit.com/r/YouTube_Startups/", "tags": ["video", "youtube", "podcasts", "reddit"]},
        {"title": "r/content_marketing Audio Audience Growth", "platform": "Reddit", "category": "Audience Marketing", "memberCount": "135,000+ members", "description": "Guest cross-promotion, Apple Podcasts SEO keywords, newsletter syndication, and sponsor pitch decks.", "joinUrl": "https://www.reddit.com/r/content_marketing/", "tags": ["marketing", "sponsorships", "audience", "reddit"]},
        {"title": "r/sounddesign Audio Atmosphere", "platform": "Reddit", "category": "Audio Branding", "memberCount": "62,000+ members", "description": "Podcast intro sonic branding, audio transition stingers, and atmospheric room tone blending.", "joinUrl": "https://www.reddit.com/r/sounddesign/", "tags": ["sound-design", "stingers", "branding", "reddit"]},
        {"title": "r/interviews Interviewing Mastery", "platform": "Reddit", "category": "Host Technique", "memberCount": "28,000+ members", "description": "Host question sequencing, active listening techniques, drawing out non-obvious stories from guests.", "joinUrl": "https://www.reddit.com/r/interviews/", "tags": ["interviewing", "hosting", "technique", "reddit"]},
        {"title": "r/Journalism Narrative Reporting", "platform": "Reddit", "category": "Journalistic Standards", "memberCount": "110,000+ members", "description": "Investigative podcast research, ethics, fact-checking workflows, and narrative episode structure.", "joinUrl": "https://www.reddit.com/r/Journalism/", "tags": ["journalism", "ethics", "investigative", "reddit"]},
        {"title": "r/media Broadcast Industry", "platform": "Reddit", "category": "Media Distribution", "memberCount": "45,000+ members", "description": "Spotify Megaphone dynamic ad insertion, iHeartRadio syndication, and programmatic audio programmatic ads.", "joinUrl": "https://www.reddit.com/r/media/", "tags": ["media", "ads", "syndication", "reddit"]},
        {"title": "r/storytelling Narrative Structure", "platform": "Reddit", "category": "Narrative Arc", "memberCount": "95,000+ members", "description": "Crafting compelling story hooks, tension building, character arcs, and satisfying narrative conclusions.", "joinUrl": "https://www.reddit.com/r/storytelling/", "tags": ["storytelling", "narrative", "podcast", "reddit"]},
        {"title": "Podcasting Community Discord", "platform": "Discord", "category": "Podcast Creators", "memberCount": "38,000+ members", "description": "The premier Discord community for podcast hosts, producers, sound engineers, and show editors.", "joinUrl": "https://discord.gg/podcasting", "tags": ["podcasting", "hosts", "discord"]},
        {"title": "Audio Engineering Collective Discord", "platform": "Discord", "category": "Mixing & Clean Up", "memberCount": "44,000+ members", "description": "Vocal track clean-up using iZotope RX, gain staging advice, and microphone shootouts.", "joinUrl": "https://discord.gg/audioengineering", "tags": ["audio", "izotope", "discord"]},
        {"title": "Voice Actors Guild Discord", "platform": "Discord", "category": "Vocal Talent", "memberCount": "41,000+ members", "description": "Casting calls for podcasts, audio drama auditions, and vocal warmup exercises.", "joinUrl": "https://discord.gg/voiceacting", "tags": ["voiceacting", "talent", "discord"]},
        {"title": "Content Creators Hub Discord", "platform": "Discord", "category": "Cross-Platform Media", "memberCount": "68,000+ members", "description": "Sharing short-form video clips from podcast recordings, TikTok growth, and audience engagement.", "joinUrl": "https://discord.gg/creators", "tags": ["creators", "video", "discord"]},
        {"title": "Sound Designers Lounge Discord", "platform": "Discord", "category": "Audio Post-Production", "memberCount": "32,000+ members", "description": "Custom sound effects libraries, Foley recording techniques, and theme music composition.", "joinUrl": "https://discord.gg/sounddesign", "tags": ["sound-design", "foley", "discord"]},
        {"title": "YouTube & Podcast Network Discord", "platform": "Discord", "category": "Video Podcasting", "memberCount": "82,000+ members", "description": "Optimizing YouTube podcast RSS ingestion, automated chapter timestamps, and retention analytics.", "joinUrl": "https://discord.gg/youtube", "tags": ["youtube", "video-podcasts", "discord"]},
        {"title": "Podcast Creators Telegram", "platform": "Telegram", "category": "Industry News", "memberCount": "31,000+ members", "description": "Daily alerts on audio industry shifts, hosting platform pricing updates, and podcast grant applications.", "joinUrl": "https://t.me/podcasters", "tags": ["podcasting", "news", "telegram"]},
        {"title": "Audio Engineering Insights Telegram", "platform": "Telegram", "category": "Audio Production", "memberCount": "39,000+ members", "description": "Tutorials on removing background hiss, managing room reverb, and mastering for Apple Podcasts.", "joinUrl": "https://t.me/audioengineering", "tags": ["audio", "mastering", "telegram"]},
        {"title": "Voice Artists Network Telegram", "platform": "Telegram", "category": "Voiceover Jobs", "memberCount": "27,000+ members", "description": "Commercial and podcast intro voiceover casting notices and vocal health tips.", "joinUrl": "https://t.me/voiceacting", "tags": ["voiceacting", "gigs", "telegram"]},
        {"title": "Media Creators Daily Telegram", "platform": "Telegram", "category": "Digital Media", "memberCount": "45,000+ members", "description": "Case studies on podcast monetization, dynamic ad placement, and private subscriber feeds.", "joinUrl": "https://t.me/creators", "tags": ["media", "monetization", "telegram"]},
        {"title": "Podcast Movement Community", "platform": "Forum", "category": "Industry Conferences", "memberCount": "85,000+ members", "description": "The world's largest gathering of podcasters sharing monetization, networking, and growth insights.", "joinUrl": "https://podcastmovement.com", "tags": ["podcastmovement", "conference", "forum"]},
        {"title": "Sound On Sound Recording Forum", "platform": "Forum", "category": "Pro Audio Techniques", "memberCount": "260,000+ members", "description": "Expert advice on broadcast microphones, room acoustic treatment, and transparent vocal compression.", "joinUrl": "https://www.soundonsound.com/forum", "tags": ["soundonsound", "recording", "forum"]},
        {"title": "Gearspace Broadcast & Podcast Forum", "platform": "Forum", "category": "Broadcast Gear", "memberCount": "380,000+ members", "description": "In-depth reviews of podcast mixers (Rodecaster Pro, Zoom PodTrak) and studio audio chains.", "joinUrl": "https://gearspace.com/board/", "tags": ["gearspace", "broadcast", "forum"]},
        {"title": "Transom Audio Storytelling", "platform": "Forum", "category": "Narrative Craft", "memberCount": "95,000+ members", "description": "Public radio and narrative podcasting workshops, gear guides, and masterclass storytelling essays.", "joinUrl": "https://transom.org", "tags": ["transom", "storytelling", "forum"]},
        {"title": "Podnews Global Audio Industry", "platform": "Forum", "category": "Industry Intelligence", "memberCount": "120,000+ members", "description": "Daily global podcast industry news, platform acquisitions, technical specs, and listener research.", "joinUrl": "https://podnews.net", "tags": ["podnews", "industry", "forum"]}
    ]
}

# 1. Update niche_communities_database.json
with open(DB_JSON_PATH, "r", encoding="utf-8") as f:
    existing_db = json.load(f)

for cat_name, items in NEW_POOLS.items():
    existing_db[cat_name] = items
    print(f"Added {len(items)} communities for category '{cat_name}'")

with open(DB_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(existing_db, f, indent=2)

print("Saved updated data/niche_communities_database.json")

# 2. Update allowed_domains in test_real_community_links.py
with open(TEST_FILE_PATH, "r", encoding="utf-8") as f:
    test_code = f.read()

new_allowed = [
    '"forum.bubble.io"',
    '"community.zapier.com"',
    '"community.airtable.com"',
    '"community.make.com"',
    '"forum.golangbridge.org"',
    '"community.cncf.io"',
    '"forum.figma.com"',
    '"gearspace.com"',
    '"kvraudio.com"',
    '"modwiggler.com"',
    '"soundonsound.com"',
    '"early-retirement.org"',
    '"mrmoneymustache.com"',
    '"choosefi.com"',
    '"community.upwork.com"',
    '"community.fiverr.com"',
    '"onlinejobs.ph"',
    '"freelancersunion.org"',
    '"podcastmovement.com"',
    '"transom.org"',
    '"podnews.net"',
    '"growthhackers.com"',
    '"moz.com"',
    '"community.hubspot.com"',
    '"blackhatworld.com"',
    '"designernews.co"',
    '"dribbble.com"',
    '"behance.net"'
]

for d in new_allowed:
    clean_d = d.replace('"', '')
    if clean_d not in test_code:
        # insert before the closing parenthesis of allowed_domains
        test_code = test_code.replace(
            '"community.home-assistant.io"\n        )',
            f'"community.home-assistant.io",\n            {d}\n        )'
        )

with open(TEST_FILE_PATH, "w", encoding="utf-8") as f:
    f.write(test_code)
print("Updated test_real_community_links.py allowed domains")

# 3. Update find_matching_category in community_database.py
with open(COMM_DB_PATH, "r", encoding="utf-8") as f:
    comm_code = f.read()

# Add precision rules for Sites 91-100 before general keywords
precision_rules = '''    # Sites 91-100 Precision Mappings
    if any(k in combined for k in ["yield farming", "staking alpha", "concentrated liquidity", "impermanent loss", "layer-2 staking"]):
        return "defi_yield_farming"
    if any(k in combined for k in ["bubble.io", "bubble responsive", "make.com", "airtable backends", "no-code web apps"]):
        return "nocode_bubble"
    if any(k in combined for k in ["golang", "go microservices", "grpc protocols", "kafka streaming", "goroutines"]):
        return "golang_microservices"
    if any(k in combined for k in ["growth marketing", "programmatic seo", "virality loops", "conversion rate experiments"]):
        return "growth_marketing"
    if any(k in combined for k in ["design systems", "figma component", "auto-layout", "wcag accessibility", "design tokens"]):
        return "ui_ux_design"
    if any(k in combined for k in ["electronic music", "sound design", "ableton", "modular eurorack", "synthesizer hub", "mixing sub-bass"]):
        return "music_production_audio"
    if any(k in combined for k in ["fire movement", "safe withdrawal rate", "financial independence hub"]):
        return "fire_movement"
    if any(k in combined for k in ["virtual assistant", "remote operations hub", "hiring in philippines", "sop creation"]):
        return "virtual_assistants"
    if any(k in combined for k in ["podcast creator", "audio syndication", "multi-track recording", "dynamic podcast ad"]):
        return "podcast_creators"
'''

if "Sites 91-100 Precision Mappings" not in comm_code:
    comm_code = comm_code.replace(
        "    # Sites 71-80 Precision Mappings\n",
        precision_rules + "    # Sites 71-80 Precision Mappings\n"
    )
    with open(COMM_DB_PATH, "w", encoding="utf-8") as f:
        f.write(comm_code)
    print("Updated community_database.py with Sites 91-100 precision mappings")
else:
    print("community_database.py already contains Sites 91-100 precision mappings")
